namespace: myproject
namespace_desc: "My Demo Projecty"

openshift_cluster_content:
- object: Projects
  content:
  - name: Demo Project
    template: "{{ inventory_dir }}/templates/project-template.yml"
    action: create
    params_from_vars:
      NAMESPACE: "{{ namespace }}"
      NAMESPACE_DISPLAY_NAME: "{{ namespace_desc }}"
    tags:
    - projects

- object: Secrets
  post_steps:
    - role: "{{ inventory_dir }}/../roles/link-secrets"
      vars:
        secret_name: my-registry-secret
        # Hacky setting tmp_dep_dir to empty string here!
        # Otherwise the pre-post-step task SILENTLY fails because tmp_dep_dir is undefined. HA!
        tmp_dep_dir:
  content:
  - name: Registry Secret
    template: "{{ inventory_dir }}/templates/secret-docker-cfg-stringdata.yml"
    params_from_vars:
      NAME: my-registry-secret
      REPO_FQDN: my-registry.example.com
      REPO_AUTH: fzzzzbzbzzbzbzzbzzzzzzzzzbzzzz
    tags:
    - secrets
